token: "CEhyyhaCbXgLuTVs"    # Lidraughts OAuth2 Token.
url: "https://lidraughts.org/"  # Lidraughts base URL.
engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing engines, relative to this project.
  name: "scan"               # Binary name of the engine to use.
  engine_arguement: "hub"
  protocol: "hub"            # "hub", "dxp", "cb" (checkerboard) or "strategy"
  ponder: true               # Think on opponent's time.
# engine_options:            # Any custom command line params to pass to the engine.
#   cpuct: 3.1
  homemade_options:
#   Hash: 256
  hub_options:
    book-ply: 20
    tt-size: 23
    bb-size: 'auto'          # 'auto' changes bb depending on the variant
#   go_commands:             # Additional options to pass to the Hub engine.
#     nodes: 1               # Search so many nodes only.
#     depth: 5               # Search depth ply only.
#     movetime: 1000         # Integer. Search exactly movetime milliseconds.
  dxp_options:
    engine_opened: true
  cb_options:
    divide-time-by: 40
  silence_stderr: false      # Some engines (yes you, Leela) are very noisy.

abort_time: 20               # Time to abort a game in seconds when there is no activity.
fake_think_time: true        # Artificially slow down the bot to pretend like it's thinking.
rate_limiting_delay: 0       # Time (in ms) to delay after sending a move to prevent "Too Many Requests" errors.
move_overhead: 5000          # Increase if your bot flags games too often.
move_overhead_inc: 5000      # Works like Move Overhead in Stockfish

correspondence:
    move_time: 60            # Time in seconds to search in correspondence games.
    checkin_period: 600      # How often to check for opponent moves in correspondence games after disconnecting.
    disconnect_time: 300     # Time before disconnecting from a correspondence game.
    ponder: false            # Ponder in correspondence games the bot is connected to.

challenge:                   # Incoming challenges.
  concurrency: 1             # Number of games to play simultaneously.
  sort_by: "first"           # Possible values: "best" and "first".
  accept_bot: true           # Accepts challenges coming from other bots.
  only_bot: false            # Accept challenges by bots only.
  max_increment: 180         # Maximum amount of increment to accept a challenge. The max is 180. Set to 0 for no increment.
  min_increment: 0           # Minimum amount of increment to accept a challenge.
  max_base: 315360000        # Maximum amount of base time to accept a challenge. The max is 315360000 (10 years).
  min_base: 0                # Minimum amount of base time to accept a challenge.
  variants:                  # Draughts variants to accept (https://lidraughts.org/variant).
    - standard
#   - fromPosition
    - breakthrough
    - antidraughts
    - frisian
    - frysk
#   - brazilian
#   - russian
  time_controls:             # Time controls to accept.
    - ultraBullet
    - bullet
    - blitz
    - rapid
#   - classical
#   - correspondence
  modes:                     # Game modes to accept.
    - casual                 # Unrated games.
#   - rated                  # Rated games - must comment if the engine doesn't try to win.

